### ISSUE TITLE
problem with textClassifierHATT.py, thank you

### ISSUE THREAD

**Issue by ericalingyuan** [richliao/textClassifier#6]
Traceback (most recent call last):
  File "textClassifierHATT.py", line 203, in <module>
    l_dense_sent = TimeDistributed(Dense(200,input_shape=(200,)))(l_lstm_sent)
  File "/usr/local/lib/python2.7/dist-packages/Keras-2.0.4-py2.7.egg/keras/engine/topology.py", line 569, in __call__
    self.assert_input_compatibility(inputs)
  File "/usr/local/lib/python2.7/dist-packages/Keras-2.0.4-py2.7.egg/keras/engine/topology.py", line 440, in assert_input_compatibility
    str(K.ndim(x)))
ValueError: Input 0 is incompatible with layer time_distributed_4: expected ndim=3, found ndim=4

**Comment by scpei** [comment]
Hello,
I have same error with you.
Have you fixed it?
Thanks

**Comment by thomasnt13** [comment]
same error... plz help

**Comment by dy-octa** [comment]
Try use keras1.2.2 rather than keras2

**Comment by maoyanying** [comment]
I have the same erro. How did you deal with it??I will wait your answer.Thanks a lot !

**Comment by ericalingyuan** [comment]
Sorry, I still cannot solve this issue.

**Comment by maoyanying** [comment]
so ,did you find other code which can implementate the paper of Hierarchical Attention Networks for Document Classification?

**Comment by ericalingyuan** [comment]
check this code, https://github.com/thunlp/NSC. Based on their paper, I think NSC+LA is the same Hierarchical Attention Networks. That code works well.

**Comment by maoyanying** [comment]
Thank you.check this code,https://github.com/ematvey/deep-text-classifier,Based on the paper of Hierarchical Attention Networks for Document Classification,but have some problem.

**Comment by maoyanying** [comment]
https://github.com/ematvey/deep-text-classifier

**Comment by ericalingyuan** [comment]
Thanks a lot for sharing this with me :-)

**Comment by maoyanying** [comment]
Did you run the work of https://github.com/ematvey/deep-text-classifier?   @ericalingyuan

**Comment by maoyanying** [comment]
Did you try to use keras1.2.2 rather than keras2 in this work?

**Comment by dy-octa** [comment]
(Simply use keras1.2. The problem is due to incompatibility.)

**Comment by Mining-multiple-repos-data** [comment]
I used Keras1.2 still getting the same error, can anyone please help with this?

**Comment by Mining-multiple-repos-data** [comment]
Hey!! Finally it works - with 1.2.2 version, but not 1.2

**Comment by prernakhurana2** [comment]
How will it work with the latest keras version-2.0.2 ??

**Comment by maoyanying** [comment]
it may not work.

**Comment by prernakhurana2** [comment]
It is throwing error at this line---
l_dense_sent = TimeDistributed(Dense(200,input_shape=(200,)))(l_lstm_sent)
but not at this ---
l_dense = TimeDistributed(Dense(200))(l_lstm)

If it is due to version, then should it not throw error at the above line as well

**Comment by maoyanying** [comment]
it works with1. 2.2version Keras.
